# Use the official MongoDB image from the Docker Hub as a base image
FROM mongo:latest

# Set environment variables for MongoDB
# ENV MONGO_INITDB_ROOT_USERNAME mongodb
# ENV MONGO_INITDB_ROOT_PASSWORD mongodb123

# Expose MongoDB port
EXPOSE 27017
